# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_NFS_DIR = "/vagrant-nfs"
VAGRANT_WORKSPACE_DIR = "/home/vagrant/workspace"
PRIVATE_IP = "192.168.33.10"
host_workspace_directory = Dir.pwd + "/../workspace"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "private_network", ip: PRIVATE_IP

  config.vm.synced_folder host_workspace_directory, VAGRANT_NFS_DIR, type: :nfs
  config.bindfs.bind_folder VAGRANT_NFS_DIR, VAGRANT_WORKSPACE_DIR

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
