---
- name: "Update apt cache"
  become: true
  apt:
    update_cache: true

- name: "Install required packages"
  become: true
  apt: name={{item}}
  with_items:
    - vim
    - pkg-config
    - qt-sdk
